### ISSUE TITLE
Add support for determining hole esdf layer

### ISSUE THREAD

**Issue by jmblixt3** [GOFIRST-Robotics/Lunabotics#127]
Obtain esdf once you have the below group height, then utilize this data to then determine where holes are.

**Comment by jmblixt3** [comment]
@BergerKing333 this is done right

**Comment by BergerKing333** [comment]
Im not totally sure what this task entails... we can get 2 different esdf slices, and set those heights based on a config file rather than hardcoded into the c++. We've also found general heights that seem to work, but don't have any logic to tell us which height the holes are going to be visible at

**Comment by jmblixt3** [comment]
Floor is automatically calibrated at zero. So anything slightly below that
is a reasonable hole height. More testing and validation should be
performed. Ie record more sand pit. But code should work.
